version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - cd client
      - npm -v
      - pwd
      - npm install
      - ls -a
      - echo Installing dependencies...
     

  build:
    commands:
      - echo Building the app...
      - npm run build

  post_build:
    commands:
      - echo Build complete.
      - echo "Zipping app..."
      - zip -r app.zip .
      - echo "Cloning GitHub repo..."
      - git config --global user.email "aswinjothishsm@gmail.com"
      - git config --global user.name "Maliciouus"
      - git clone https://github.com/Maliciouus/musician-app-master.git
      - cd musician-app-master
      - git checkout -b build-artifacts || git checkout build-artifacts
      - cp ../app.zip .
      - git add app.zip
      - git commit -m "Add new build artifact"
      - git push origin build-artifacts
artifacts:
  files:
    - '**/*'
base-directory: dist
